import type { ExamRequestCategory } from "./cabinetTypes";

// Category labels are localised at render time via i18n; these are the French
// defaults used by the printed document (which is always French in Morocco).
export const EXAM_REQ_CATEGORY_LABELS: Record<ExamRequestCategory, string> = {
  biologie:    "Biologie",
  radiologie:  "Radiologie",
  echographie: "Échographie",
  scanner:     "Scanner (TDM)",
  irm:         "IRM",
  autre:       "Autre",
};

export const EXAM_REQ_CATEGORY_COLORS: Record<ExamRequestCategory, string> = {
  biologie:    "#E85B5B",
  radiologie:  "#1890C5",
  echographie: "#15A876",
  scanner:     "#9B72D0",
  irm:         "#D4962A",
  autre:       "#6B7280",
};

export const EXAM_REQ_CATEGORIES: ExamRequestCategory[] =
  ["biologie", "radiologie", "echographie", "scanner", "irm", "autre"];

// Common exams per category — used as datalist suggestions so the doctor types
// fast. Not exhaustive; the field is free text.
export const EXAM_CATALOG: Record<ExamRequestCategory, string[]> = {
  biologie: [
    "NFS (Numération Formule Sanguine)",
    "Glycémie à jeun",
    "Hémoglobine glyquée (HbA1c)",
    "Créatininémie",
    "Urée sanguine",
    "Ionogramme sanguin",
    "Bilan lipidique (Cholestérol, Triglycérides)",
    "Bilan hépatique (ASAT, ALAT, GGT, PAL)",
    "TSH",
    "T4 libre",
    "CRP (Protéine C-réactive)",
    "Vitesse de sédimentation (VS)",
    "TP / INR",
    "TCA",
    "Ferritinémie",
    "Fer sérique",
    "Calcémie",
    "Phosphorémie",
    "Magnésémie",
    "Acide urique (Uricémie)",
    "Vitamine D (25-OH)",
    "Vitamine B12",
    "Albuminémie / Protidémie",
    "Bilan martial",
    "Amylasémie / Lipasémie",
    "CPK",
    "Troponine",
    "BNP / NT-proBNP",
    "Groupe sanguin / Rhésus",
    "Sérologie hépatite B (Ag HBs)",
    "Sérologie hépatite C",
    "Sérologie VIH",
    "Bêta-HCG plasmatique",
    "PSA (Antigène prostatique)",
    "ECBU (Examen cytobactériologique des urines)",
    "Protéinurie de 24h",
    "Microalbuminurie",
    "Coproculture",
    "Prélèvement vaginal",
  ],
  radiologie: [
    "Radiographie thoracique (face)",
    "Radiographie thoracique (face + profil)",
    "Radiographie de l'abdomen sans préparation (ASP)",
    "Radiographie du rachis cervical",
    "Radiographie du rachis lombaire (face + profil)",
    "Radiographie du bassin",
    "Radiographie du genou",
    "Radiographie de l'épaule",
    "Radiographie de la cheville",
    "Radiographie du poignet / main",
    "Radiographie des sinus",
    "Panoramique dentaire",
    "Mammographie",
  ],
  echographie: [
    "Échographie abdominale",
    "Échographie abdomino-pelvienne",
    "Échographie pelvienne",
    "Échographie rénale / voies urinaires",
    "Échographie thyroïdienne",
    "Échographie mammaire",
    "Échographie des parties molles",
    "Échographie testiculaire",
    "Échographie cardiaque (échocardiographie)",
    "Écho-Doppler des membres inférieurs (veineux)",
    "Écho-Doppler des membres inférieurs (artériel)",
    "Écho-Doppler des troncs supra-aortiques",
    "Échographie obstétricale",
  ],
  scanner: [
    "TDM cérébrale (sans injection)",
    "TDM cérébrale (avec injection)",
    "TDM thoracique",
    "TDM abdomino-pelvienne",
    "TDM du rachis lombaire",
    "Angio-TDM thoracique",
    "Uro-scanner",
    "TDM des sinus",
  ],
  irm: [
    "IRM cérébrale",
    "IRM médullaire (rachis cervical)",
    "IRM médullaire (rachis lombaire)",
    "IRM du genou",
    "IRM de l'épaule",
    "IRM abdominale",
    "IRM pelvienne",
    "Angio-IRM cérébrale",
  ],
  autre: [
    "Électrocardiogramme (ECG)",
    "Épreuve d'effort",
    "Holter ECG (24h)",
    "Holter tensionnel (MAPA)",
    "Spirométrie / EFR",
    "Électroencéphalogramme (EEG)",
    "Électromyogramme (EMG)",
    "Fibroscopie digestive haute",
    "Coloscopie",
    "Fond d'œil",
  ],
};
